items:
  '1':
    material: WOODEN_SWORD
    name: WOODEN_SWORD
  '2':
    material: STONE_SWORD
    name: STONE_SWORD
  '3':
    material: GOLDEN_SWORD
    name: GOLDEN_SWORD
  '4':
    material: IRON_SWORD
    name: IRON_SWORD
  '5':
    material: DIAMOND_SWORD
    name: DIAMOND_SWORD
  '6':
    material: WOODEN_SHOVEL
    name: WOODEN_SHOVEL
  '7':
    material: STONE_SHOVEL
    name: STONE_SHOVEL
  '8':
    material: GOLDEN_SHOVEL
    name: GOLDEN_SHOVEL
  '9':
    material: IRON_SHOVEL
    name: IRON_SHOVEL
  '10':
    material: DIAMOND_SHOVEL
    name: DIAMOND_SHOVEL
  '11':
    material: WOODEN_PICKAXE
    name: WOODEN_PICKAXE
  '12':
    material: STONE_PICKAXE
    name: STONE_PICKAXE
  '13':
    material: GOLDEN_PICKAXE
    name: GOLDEN_PICKAXE
  '14':
    material: IRON_PICKAXE
    name: IRON_PICKAXE
  '15':
    material: DIAMOND_PICKAXE
    name: DIAMOND_PICKAXE
  '16':
    material: WOODEN_AXE
    name: WOODEN_AXE
  '17':
    material: STONE_AXE
    name: STONE_AXE
  '18':
    material: GOLDEN_AXE
    name: GOLDEN_AXE
  '19':
    material: DIAMOND_AXE
    name: DIAMOND_AXE
  '20':
    material: WOODEN_HOE
    name: WOODEN_HOE
  '21':
    material: STONE_HOE
    name: STONE_HOE
  '22':
    material: GOLDEN_HOE
    name: GOLDEN_HOE
  '23':
    material: IRON_HOE
    name: IRON_HOE
  '24':
    material: DIAMOND_HOE
    name: DIAMOND_HOE
  '25':
    material: APPLE
    name: APPLE
  '26':
    material: BREAD
    name: BREAD
  '27':
    material: COOKED_PORKCHOP
    name: COOKED_PORKCHOP
  '28':
    material: DISPENSER
    name: DISPENSER
  '29':
    material: NOTE_BLOCK
    name: NOTE_BLOCK
  '30':
    material: REDSTONE_BLOCK
    name: REDSTONE_BLOCK
  '31':
    material: TARGET
    name: TARGET
  '32':
    material: TRIPWIRE_HOOK
    name: TRIPWIRE_HOOK
  '33':
    material: OBSERVER
    name: OBSERVER
  '34':
    material: LIGHT_WEIGHTED_PRESSURE_PLATE
    name: LIGHT_WEIGHTED_PRESSURE_PLATE
  '35':
    material: TRAPPED_CHEST
    name: TRAPPED_CHEST
  '36':
    material: REDSTONE_LAMP
    name: REDSTONE_LAMP
  '37':
    material: BEACON
    name: BEACON
  '38':
    material: SCUTE
    name: SCUTE
  '39':
    material: LAPIS_LAZULI
    name: LAPIS_LAZULI
  '40':
    material: SLIME_BALL
    name: SLIME_BALL
  '41':
    material: LEATHER
    name: LEATHER
  '42':
    material: WHEAT
    name: WHEAT
  '43':
    material: BONE
    name: BONE
  '44':
    material: EMERALD_BLOCK
    name: EMERALD_BLOCK
  '45':
    material: NETHER_QUARTZ_ORE
    name: NETHER_QUARTZ_ORE
  '46':
    material: MINECART
    name: MINECART
  '47':
    material: ELYTRA
    name: ELYTRA
  '48':
    material: TNT_MINECART
    name: TNT_MINECART
  '49':
    material: RAIL
    name: RAIL
  '50':
    material: OAK_BOAT
    name: OAK_BOAT
  '51':
    material: GOLDEN_HELMET
    name: GOLDEN_HELMET
  '52':
    material: CHAINMAIL_CHESTPLATE
    name: CHAINMAIL_CHESTPLATE
  '53':
    material: LEATHER_LEGGINGS
    name: LEATHER_LEGGINGS
  '54':
    material: DIAMOND_BOOTS
    name: DIAMOND_BOOTS
  '55':
    material: CRAFTING_TABLE
    name: CRAFTING_TABLE
  '56':
    material: FURNACE
    name: FURNACE
  '57':
    material: ENCHANTING_TABLE
    name: ENCHANTING_TABLE
  '58':
    material: END_PORTAL_FRAME
    name: END_PORTAL_FRAME
  '59':
    material: WITHER_ROSE
    name: WITHER_ROSE
  '60':
    material: JUNGLE_LEAVES
    name: JUNGLE_LEAVES
  '61':
    material: CACTUS
    name: CACTUS
  '62':
    material: BIRCH_LOG
    name: BIRCH_LOG
  '63':
    material: WET_SPONGE
    name: WET_SPONGE
  '64':
    material: BOOKSHELF
    name: BOOKSHELF
  '65':
    material: REDSTONE_ORE
    name: REDSTONE_ORE
  '66':
    material: CARVED_PUMPKIN
    name: CARVED_PUMPKIN
  '67':
    material: NETHERRACK
    name: NETHERRACK
  '68':
    material: SOUL_SAND
    name: SOUL_SAND
  '69':
    material: DIAMOND_BLOCK
    name: DIAMOND_BLOCK
  '70':
    material: MYCELIUM
    name: MYCELIUM
  '71':
    material: MELON
    name: MELON
  '72':
    material: OAK_SAPLING
    name: OAK_SAPLING
  '73':
    material: CARROT
    name: CARROT
  '74':
    material: HONEY_BOTTLE
    name: HONEY_BOTTLE
  '75':
    material: HEART_OF_THE_SEA
    name: HEART_OF_THE_SEA
